In [12]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [26]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')


In [27]:
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [137]:
print("The No. Of rows in dataset", len(dataset))
print("The No. Of rows in dataset", len(dataset.columns))


The No. Of rows in dataset 1338
The No. Of rows in dataset 7


In [29]:
dataset = pd.get_dummies(dataset, columns=['sex'])

age     sex     bmi  children      charges  smoker_yes
0      19  female  27.900         0  16884.92400        True
1      18    male  33.770         1   1725.55230       False
2      28    male  33.000         3   4449.46200       False
3      33    male  22.705         0  21984.47061       False
4      32    male  28.880         0   3866.85520       False
...   ...     ...     ...       ...          ...         ...
1333   50    male  30.970         3  10600.54830       False
1334   18  female  31.920         0   2205.98080       False
1335   18  female  36.850         0   1629.83350       False
1336   21  female  25.800         0   2007.94500       False
1337   61  female  29.070         0  29141.36030        True

[1338 rows x 6 columns]

In [31]:
#datasets=pd.get_dummies(dataset,drop_first=True)
datasets = pd.get_dummies(dataset, columns=['smoker'], drop_first=True)

In [32]:
datasets

age     bmi  children      charges  sex_female  sex_male  smoker_yes
0      19  27.900         0  16884.92400        True     False        True
1      18  33.770         1   1725.55230       False      True       False
2      28  33.000         3   4449.46200       False      True       False
3      33  22.705         0  21984.47061       False      True       False
4      32  28.880         0   3866.85520       False      True       False
...   ...     ...       ...          ...         ...       ...         ...
1333   50  30.970         3  10600.54830       False      True       False
1334   18  31.920         0   2205.98080        True     False       False
1335   18  36.850         0   1629.83350        True     False       False
1336   21  25.800         0   2007.94500        True     False       False
1337   61  29.070         0  29141.36030        True     False        True

[1338 rows x 7 columns]

In [33]:
#indep=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
#dep=datasets[['Profit']]
datasets.columns


Index(['age', 'bmi', 'children', 'charges', 'sex_female', 'sex_male',
       'smoker_yes'],
      dtype='object')

In [36]:
indep=datasets[['age', 'bmi', 'children', 'sex_female', 'sex_male',
       'smoker_yes']]
dep = datasets[['charges']]

In [37]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [133]:
from sklearn.svm import SVR
regressor=SVR(kernel="linear",C=3000)
regressor=regressor.fit(X_train,y_train)

C:\Users\kgopi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [134]:
y_pred=regressor.predict(X_test)

In [135]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [136]:
r_score

0.6662689347124363

In [128]:
regressor.intercept_

array([2999.94633646])

In [49]:
regressor.n_support_

array([33])

In [50]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [51]:
regressor.support_vectors_

array([[1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 0.0000000e+00,
        1.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [6.5605480e+04, 1.5303206e+05, 1.0713838e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.1452361e+05, 1.2261684e+05, 2.6177623e+05, 0.0000000e+00,
        1.0000000e+00],
       [6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00,
        0.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 0.0000000e+00,
        0.0000000e+00],
       [7.8013110e+04, 1.2159755e+05, 2.6434606e+05, 0.0000000e+00,
        0.0000000e+00],
       [2.3640930e+04, 9.6189630e+04, 1.4800111e+05, 0.0000000e+00,
        0.0000000e+00],
       [7.6253860e+04, 1.1386730e+05, 2.9866447e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.5505730e+04, 1.2738230e+05, 3.5534170e+04, 0.0000000e+00,
        1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        1.00

In [52]:
regressor.coef_

array([[ 0.76394145,  0.04655444,  0.04389052,  0.28454473, -0.10738669]])

In [53]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D:2000
Admin400
Marketing 4000
State_flo 0 or 1:0
State_new 0 or 1:0


In [54]:
result=regressor.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

C:\Anaconda3\envs\ML\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"


In [55]:
result

array([42943.67266674])