In [13]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [14]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')


In [15]:
dataset

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [16]:
print("The No. Of rows in dataset", len(dataset))
print("The No. Of rows in dataset", len(dataset.columns))


The No. Of rows in dataset 400
The No. Of rows in dataset 5


In [17]:
#dataset = pd.get_dummies(dataset, columns=['sex'])

In [18]:
datasets=pd.get_dummies(dataset,drop_first=True)
#datasets = pd.get_dummies(dataset, columns=['smoker'], drop_first=True)

In [19]:
datasets

User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0         True
1    15810944   35            20000          0         True
2    15668575   26            43000          0        False
3    15603246   27            57000          0        False
4    15804002   19            76000          0         True
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1        False
396  15706071   51            23000          1         True
397  15654296   50            20000          1        False
398  15755018   36            33000          0         True
399  15594041   49            36000          1        False

[400 rows x 5 columns]

In [20]:
#datasets = datasets.drop(columns=["User ID"])
datasets = datasets.drop("User ID", axis=1)

In [21]:
#indep=datasets[['R&D Spend','Administration', 'Marketing Spend','State_Florida', 'State_New York']]
#dep=datasets[['Profit']]
datasets.columns


Index(['Age', 'EstimatedSalary', 'Purchased', 'Gender_Male'], dtype='object')

In [22]:
indep=datasets[['Age', 'EstimatedSalary', 'Gender_Male']]
dep = datasets[['Purchased']]

In [23]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [24]:
from sklearn.svm import SVC
classifer=SVC(kernel="linear",C=3000)
classifer=classifer.fit(X_train,y_train)

C:\Users\kgopi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [26]:
y_pred=classifer.predict(X_test)

In [27]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [28]:
cm

array([[78,  7],
       [13, 36]])

In [29]:
from sklearn.metrics import classification_report
rep = classification_report(y_test, y_pred)

In [30]:
print(rep)

              precision    recall  f1-score   support

           0       0.86      0.92      0.89        85
           1       0.84      0.73      0.78        49

    accuracy                           0.85       134
   macro avg       0.85      0.83      0.83       134
weighted avg       0.85      0.85      0.85       134



In [128]:
regressor.intercept_

array([2999.94633646])

In [49]:
regressor.n_support_

array([33])

In [50]:
regressor.support_

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])

In [51]:
regressor.support_vectors_

array([[1.0002300e+03, 1.2415304e+05, 1.9039300e+03, 0.0000000e+00,
        1.0000000e+00],
       [5.4205000e+02, 5.1743150e+04, 0.0000000e+00, 0.0000000e+00,
        1.0000000e+00],
       [6.5605480e+04, 1.5303206e+05, 1.0713838e+05, 0.0000000e+00,
        1.0000000e+00],
       [1.1452361e+05, 1.2261684e+05, 2.6177623e+05, 0.0000000e+00,
        1.0000000e+00],
       [6.1994480e+04, 1.1564128e+05, 9.1131240e+04, 1.0000000e+00,
        0.0000000e+00],
       [6.3408860e+04, 1.2921961e+05, 4.6085250e+04, 0.0000000e+00,
        0.0000000e+00],
       [7.8013110e+04, 1.2159755e+05, 2.6434606e+05, 0.0000000e+00,
        0.0000000e+00],
       [2.3640930e+04, 9.6189630e+04, 1.4800111e+05, 0.0000000e+00,
        0.0000000e+00],
       [7.6253860e+04, 1.1386730e+05, 2.9866447e+05, 0.0000000e+00,
        0.0000000e+00],
       [1.5505730e+04, 1.2738230e+05, 3.5534170e+04, 0.0000000e+00,
        1.0000000e+00],
       [1.2054252e+05, 1.4871895e+05, 3.1161329e+05, 0.0000000e+00,
        1.00

In [52]:
regressor.coef_

array([[ 0.76394145,  0.04655444,  0.04389052,  0.28454473, -0.10738669]])

In [53]:
rd_input=float(input("R&D:"))
admin_input=float(input("Admin"))
mark_input=float(input("Marketing "))
fol_input=int(input("State_flo 0 or 1:"))
new_input=int(input("State_new 0 or 1:"))

R&D:2000
Admin400
Marketing 4000
State_flo 0 or 1:0
State_new 0 or 1:0


In [54]:
result=regressor.predict([[rd_input,admin_input,mark_input,fol_input,new_input]])

C:\Anaconda3\envs\ML\lib\site-packages\sklearn\base.py:442: UserWarning: X does not have valid feature names, but SVR was fitted with feature names
  "X does not have valid feature names, but"


In [55]:
result

array([42943.67266674])