In [33]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SequentialFeatureSelector

In [34]:
dataset = pd.read_csv(r'D:\HopeAI\Training\Week9-ML and Data Science Capstone\1. Data Collection\real_estate_dataset.csv')
dataset

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747
1,2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386
2,3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880
3,4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996
4,5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,138.338057,2,2,2,1967,1,0,16,4.296086,5.562583,488496.350722
496,497,195.914028,2,3,1,1977,0,1,45,7.406261,2.845105,657736.921717
497,498,69.433659,1,1,2,2004,0,0,18,8.629724,6.263264,405324.950201
498,499,293.598702,5,1,3,1940,1,0,41,5.318891,16.990684,773035.968028


In [35]:
#Check of null values in rows
dataset.isnull().sum()

ID                    0
Square_Feet           0
Num_Bedrooms          0
Num_Bathrooms         0
Num_Floors            0
Year_Built            0
Has_Garden            0
Has_Pool              0
Garage_Size           0
Location_Score        0
Distance_to_Center    0
Price                 0
dtype: int64

In [36]:
dataset.columns

Index(['ID', 'Square_Feet', 'Num_Bedrooms', 'Num_Bathrooms', 'Num_Floors',
       'Year_Built', 'Has_Garden', 'Has_Pool', 'Garage_Size', 'Location_Score',
       'Distance_to_Center', 'Price'],
      dtype='object')

In [37]:
# Univariate
from Univariate import Univariate

#Seggregate Quantitative and Qualitative data
quan,qual = Univariate.Quanqual(dataset)

In [38]:
dataset[quan]

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
0,1,143.635030,1,3,3,1967,1,1,48,8.297631,5.935734,602134.816747
1,2,287.678577,1,2,1,1949,0,1,37,6.061466,10.827392,591425.135386
2,3,232.998485,1,3,2,1923,1,0,14,2.911442,6.904599,464478.696880
3,4,199.664621,5,2,2,1918,0,0,17,2.070949,8.284019,583105.655996
4,5,89.004660,4,3,3,1999,1,0,34,1.523278,14.648277,619879.142523
...,...,...,...,...,...,...,...,...,...,...,...,...
495,496,138.338057,2,2,2,1967,1,0,16,4.296086,5.562583,488496.350722
496,497,195.914028,2,3,1,1977,0,1,45,7.406261,2.845105,657736.921717
497,498,69.433659,1,1,2,2004,0,0,18,8.629724,6.263264,405324.950201
498,499,293.598702,5,1,3,1940,1,0,41,5.318891,16.990684,773035.968028


In [39]:
#Get Unique Values	Frequency	Relative Frequency	Cummulative Frequency
Univariate.getFrequency(dataset, quan)["Square_Feet"]


,Unique Values,Frequency,Relative Frequency,Cummulative Frequency
0,79.541207,1,0.002,1
1,158.462912,1,0.002,2
2,105.898960,1,0.002,3
3,127.745580,1,0.002,4
4,73.495485,1,0.002,5
...,...,...,...,...
495,132.166136,1,0.002,496
496,95.456242,1,0.002,497
497,287.678577,1,0.002,498
498,77.799371,1,0.002,499


In [40]:
#Get all values 
Univariate.CreateDataFrame(dataset, quan)

,ID,Square_Feet,Num_Bedrooms,Num_Bathrooms,Num_Floors,Year_Built,Has_Garden,Has_Pool,Garage_Size,Location_Score,Distance_to_Center,Price
Mean,250.5,174.64,2.958,1.976,1.964,1957.6,0.536,0.492,30.174,5.16441,10.4696,582210
Median,250.5,178.291,3,2,2,1959,1,0,30,5.20652,10.8861,574724
Mode,1,51.2654,1,1,2,1920,1,0,26,0.00442781,0.0628181,276892
Q1:25%,125.75,110.32,2,1,1,1926,0,0,20,2.76065,6.06675,503080
Q2:50%,250.5,178.291,3,2,2,1959,1,0,30,5.20652,10.8861,574724
Q3:75%,375.25,239.031,4,3,3,1988,1,1,41,7.73293,15.0726,665942
99%,495.01,296.554,5,3,3,2020,1,1,49,9.9021,19.725,864332
Q4:100%,500,298.241,5,3,3,2022,1,1,49,9.99544,19.928,960678
IQR,249.5,128.711,2,2,2,62,1,1,21,4.97228,9.00584,162862
1.5Rule,374.25,193.067,3,3,3,93,1.5,1.5,31.5,7.45843,13.5088,244293


In [41]:
# Bivariant
#Variance_Inflation_Factor
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [42]:
calc_vif(dataset[['Location_Score', 'Distance_to_Center']])

,variables,VIF
0,Location_Score,2.604653
1,Distance_to_Center,2.604653


In [43]:
# Independant Sample- Unpaired T Test
# Diferrent Group(Has Garden) but same contion(Price)

from scipy.stats import ttest_ind

Has_Garden = dataset[dataset['Has_Garden'] == 1]['Price']
No_Garden = dataset[dataset['Has_Garden'] == 0]['Price']
ttest_ind(Has_Garden, No_Garden)


Ttest_indResult(statistic=2.4514697900485136, pvalue=0.014569918109934582)

In [44]:
# ANAVO : Analysis of Variance
import scipy.stats as stats

g1 = dataset[dataset['Num_Floors'] == 1]['Price']
g2 = dataset[dataset['Num_Floors'] == 2]['Price']
g3 = dataset[dataset['Num_Floors'] == 3]['Price']

stats.f_oneway(g1, g2, g3)

F_onewayResult(statistic=8.907962143670218, pvalue=0.00015814211718859862)

In [45]:
X_ind = dataset.drop(columns=['ID','Price'])
Y_Dep=dataset['Price']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X_ind, Y_Dep, test_size = 1/3, random_state = 0)


In [47]:
#Preprocessing input
scx= StandardScaler()
X_train = scx.fit_transform(X_train)
X_test = scx.transform(X_test)

In [50]:
#Feature Selection
def ForwardBackwardSelection(direction, X_Train):
    
    from sklearn.linear_model import LinearRegression
    from sklearn.linear_model import LogisticRegression
    from sklearn.svm import SVC
    from sklearn.ensemble import RandomForestClassifier
    from sklearn.tree import DecisionTreeClassifier

    models = {
        "Logistic": LogisticRegression(max_iter=1000),
        "SVC": SVC(),
        "RandomForest": RandomForestClassifier(),
        "DecisionTree": DecisionTreeClassifier()
    }

    print(direction,"selection :")

    for name, model in models.items():
        
        if (direction == 'forward'):
            sfs = SequentialFeatureSelector(model, n_features_to_select=2, direction="forward")
        else:
            sfs = SequentialFeatureSelector(model, n_features_to_select=2, direction="backward",cv=5, scoring='accuracy', n_jobs=1)
        sfs.fit(X_Train, y_train)
        selected = X_Train.columns[sfs.get_support()]
        
        
        print(name, "Selected Features:", list(selected))

In [51]:
X_Train = pd.DataFrame(X_train, columns=X_ind.columns)
ForwardBackwardSelection("forward", X_Train)

forward selection :
Logistic Selected Features: ['Square_Feet', 'Num_Bedrooms']
SVC Selected Features: ['Square_Feet', 'Num_Bedrooms']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\linear_model\_logistic.py", line 1516, in fit
    check_classification_targets(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\utils\multiclass.py", line 197, in check_classification_t

RandomForest Selected Features: ['Square_Feet', 'Num_Bedrooms']
DecisionTree Selected Features: ['Square_Feet', 'Num_Bedrooms']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\ensemble\_forest.py", line 367, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\ensemble\_forest.py", line 734, in _

In [52]:
ForwardBackwardSelection("backward", X_Train)

backward selection :


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\linear_model\_logistic.py", line 1516, in fit
    check_classification_targets(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\utils\multiclass.py", line 197, in check_classification_t

C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\linear_model\_logistic.py", line 1516, in fit
    check_classification_targets(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\utils\multiclass.py", line 197, in check_classification_t

Logistic Selected Features: ['Location_Score', 'Distance_to_Center']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\svm\_base.py", line 199, in fit
    y = self._validate_targets(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\svm\_base.py", line 716, in _validate_targets
    check_classification_ta

SVC Selected Features: ['Location_Score', 'Distance_to_Center']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\ensemble\_forest.py", line 367, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\ensemble\_forest.py", line 734, in _

RandomForest Selected Features: ['Location_Score', 'Distance_to_Center']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\tree\_classes.py", line 203, in fit
    check_classification_targets(y)


DecisionTree Selected Features: ['Location_Score', 'Distance_to_Center']


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning: 
5 fits failed out of a total of 5.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\tree\_classes.py", line 203, in fit
    check_classification_targets(y)


In [53]:
scy=StandardScaler()
y_train = scy.fit_transform(y_train.values.reshape(-1,1)) # Without reshare giving error of 1D shape
y_test = scy.transform(y_test.values.reshape(-1,1))

In [54]:
# regressor=RandomForestRegressor(n_estimators=10, random_state = 0)
# regressor=regressor.fit(X_train,y_train)
# regressor

from sklearn.svm import SVR
regressor = SVR(kernel="rbf",C=1000)
regressor.fit(X_train, y_train)


C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000)

In [55]:
y_pred=regressor.predict(X_test)
y_pred

array([-1.53012058, -1.41172007, -1.19357857, -0.5375184 ,  0.07136939,
       -0.7316944 ,  1.2760159 ,  1.09443036, -0.25506424,  0.71572072,
        1.58500477, -0.85696072,  1.02338715,  1.50532191, -1.76734198,
        0.60583825, -0.38514665,  0.4019883 , -0.42002948, -0.59759855,
       -1.02468833,  2.52765682,  0.34426655, -0.95465125,  1.6347415 ,
        0.7685669 , -1.23353698,  2.18063844,  1.88083868,  1.67115506,
        0.39957614,  0.13226541, -0.06389344,  1.52231334, -0.56154678,
        0.25294092, -0.95725907, -0.95606953, -0.3235393 , -1.18642204,
        1.03275274, -0.35586043, -0.39971337,  0.24559986,  1.51032945,
        0.24021985, -0.01066137, -0.90171664, -0.02417902, -1.94358779,
       -0.13831233, -0.51135541, -0.70311749, -0.63336205, -1.299039  ,
        0.83182326, -0.40703093, -1.02772238, -1.79368343, -0.80895944,
       -1.24931917,  1.1446579 , -0.89499454,  0.87609381, -0.34992197,
        0.58658147, -0.8013555 ,  0.99401503, -0.12661653, -0.21

In [56]:
r_score=r2_score(y_test,y_pred)
r_score

0.9390033277841845

In [57]:
import pickle
filename = "finalized_model_svr.sav"
pickle.dump(regressor, open(filename,'wb'))


In [58]:
preinput= scx.transform([[1300,3,2,2,2000,1,1,30,7.5,5]])
preinput

C:\Users\kgopi\anaconda3\envs\Training\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


array([[14.89253436,  0.02797491,  0.02187655,  0.01491624,  1.22943332,
         0.96749497,  1.02124668, -0.01840826,  0.79329288, -0.98723382]])

In [59]:
loaded_model = pickle.load(open("finalized_model_svr.sav", 'rb'))
result= loaded_model.predict(preinput)
result

array([-0.03425349])

In [60]:
preoutput = scy.inverse_transform([result])
preoutput

array([[576556.62797379]])